// <auto-generated />
namespace MatchMate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AllowNullPlayer2Id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllowNullPlayer2Id));
        
        string IMigrationMetadata.Id
        {
            get { return "202503310559069_AllowNullPlayer2Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
